on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
      name: Application Server CI
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v3
          with:
            python-version: '3.9'
        - name: Update PIP
          run: |
            python -m pip install --upgrade pip
          shell: bash
        - name: Install Required Dependencies
          run: |
            pip install virtualenv
            chmod +x ./scripts/linux/install.sh
            ./scripts/linux/install.sh
          shell: bash
        - name: Create a Virtual Environment
          run: |
            virtualenv .venv/
          shell: bash
        - name: Run Tests
          run: |
            . .venv/bin/activate && python -m unittest discover -s tests
      
